# Generated by Django 5.2.1 on 2025-06-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='peactur',
            new_name='picture',
        ),
    ]
