# Generated by Django 5.2.1 on 2025-06-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_peactur_article_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
